services:
  db: 
    image: mysql:8.0.37-debian
    environment:
      MYSQL_ROOT_PASSWORD: 'root' 
      MYSQL_DATABASE: 'nestjs' 
    ports:
      - 3306:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
  app:
    build: .
    ports: 
      - 3000:3000
    volumes: 
      - .:/home/node/app