### List Events
GET http://localhost:3000/events

### Create new event
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "New Event",
    "description": "New Event",
    "date": "2017-01-01T00:00:00.000Z",
    "price": 100
}

### Instance event ID
@eventId = {{createEvent.response.body.id}}

### Get event By Id
GET http://localhost:3000/events/{{ eventId }}

### Delete Event By Id
DELETE http://localhost:3000/events/{{ eventId }}

### Patch event by id
PATCH http://localhost:3000/events/{{ eventId }}
Content-Type: application/json

{
    "name": "New Event 3",
    "price": 1060
}

### List Spots by Event ID
GET http://localhost:3000/events/{{ eventId }}/spots

### Create new spot for event
# @name createSpot
POST http://localhost:3000/events/{{ eventId }}/spots
Content-Type: application/json

{
    "name": "A{{$randomInt 1 100}}"
}

### Instance spot ID
@spotId = {{createSpot.response.body.id}}
@spotName = {{createSpot.response.body.name}}

### Get Spot by ID
GET http://localhost:3000/events/{{ eventId }}/spots/{{ spotId }}

### Update Spot by ID
PATCH http://localhost:3000/events/{{ eventId }}/spots/{{ spotId }}
Content-Type: application/json

{
    "name": "A4 Updated",
    "status": "avaiable"
}

### Delete Spot by ID
DELETE http://localhost:3000/events/{{ eventId }}/spots/{{ spotId }}


### Reserve a spot
POST http://localhost:3000/events/{{ eventId }}/reserve
Content-Type: application/json

{
    "spots": ["{{spotName}}", "A92"],
    "ticket_kind": "half",
    "email": "teste@testing.com"
}